[package]
name = "my_app"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
xdevs-no-std = { git = "https://github.com/iscar-ucm/xdevs_no_std.rs.git", branch = "main", features = [
    "alloc",
] }

[dependencies.awkernel_lib]
path = "../../awkernel_lib"
default-features = false

[dependencies.awkernel_async_lib]
path = "../../awkernel_async_lib"
default-features = false
